spring.application.name=community.theatre
## server port
#server.port=8080

#To connect locally
server.address=0.0.0.0

## DATABASE
#====================================
# local
#spring.datasource.url=jdbc:mysql://localhost:3306/esed_project
#spring.datasource.username=root
#spring.datasource.password=
# shared
#spring.datasource.url=jdbc:mysql://localhost:3306/my_database?useSSL=false&serverTimezone=UTC
#spring.datasource.url=jdbc:mysql://mysql-24f25571-collageonlineclass-5bce.g.aivencloud.com:22382/defaultdb?useSSL=true&serverTimezone=UTC
#spring.datasource.username=avnadmin
#spring.datasource.password=AVNS_IHTxiTFwJL0CFgMp0j0
#AWS
spring.datasource.url=jdbc:mysql://esed.cni04qiu0lt0.eu-west-2.rds.amazonaws.com:3306/esed_project
spring.datasource.username=admin
spring.datasource.password=Greenwich12345

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.initialization-mode=always

# JPA (Optional: For automatic table creation)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

#To upload image on cloudinary
cloudinary.cloud-name=dmoi4ummx
cloudinary.api-key=875981571999111
cloudinary.api-secret=Ery06XtxkdMFvfjGQLqCPVK1tFM

# To send email
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=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
sendgrid.api.key=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
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#Redis
spring.redis.host=esed-redis-u6qgvo.serverless.euw2.cache.amazonaws.com
spring.redis.port=6379
spring.redis.ssl=true
spring.redis.timeout=2000ms

app.seat.lock.expiry=600
app.redis.temp.seat.lock.key=seat-lock:{eventId}:{showId}:{seat}
app.redis.booked.seat.lock.key=booked_seat_lock:{eventId}:{showId}

#JWT configuration for authentication
jwt.secret=ffc3d224e1bdece062d307b672790b08b3cda9a308dba4120ed4f253b56f8eebba7e3279b428baedc301cb42f3b38ea12a6028e7935cdb35753769b2ecb3ea3c7208710049475cb47b2210f3bf13b58caa81c037c24c4edcd455b679403cd128891e536f4c34caadc91ab073620f3015c93ace81ef48cecd177ae0ad25647e64
jwt.expiration=86400000


