spring.application.name=community.theatre
## server port
#server.port=8073


#spring.datasource.url=jdbc:mysql://localhost:3306/my_database?useSSL=false&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://mysql-24f25571-collageonlineclass-5bce.g.aivencloud.com:22382/defaultdb?useSSL=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_IHTxiTFwJL0CFgMp0j0
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (Optional: For automatic table creation)
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
